### PR TITLE
Implemented scroll wheel to scroll message area. Closes #130

### LINKED ISSUE #130: Implement scrolling with mouse wheel

### PR DESCRIPTION
**Pull request by trevarj**
Simple addition. Also really nice to use, in my opinion. Let me know if I missed something! Thanks.

### CODE REVIEW

**Comment by osa1** [comment]
Thanks! One problem though: I can't select text anymore in my terminal (st). Is that the case in your terminal as well? For example, someone just pasted a link in a channel, and I can't select & copy the link anymore.

**Comment by trevarj** [comment]
Welp! 😭 Yeah, that doesn't work for me either. Too good to be true!

**Comment by osa1** [comment]
If you look at the sequence to enable these events:

```
\x1b[?1000h\x1b[?1002h\x1b[?1015h\x1b[?1006h
```

this seems to be doing 4 things -- there are 4 occurrences of `\x1b[?`. I'm wondering why we have 4 such sequences, perhaps only one or two of them are for mouse wheel events and we can get away with only enabling those.

**Comment by osa1** [comment]
I just checked [zulip-terminal][1] for how they handle mouse events: normally all events are interpreted by the application (including mouse clicks and selection), but if you press `shift` then the mouse control is given back to the terminal (until you release `shift`).

It's not ideal for tiny though: I'd rather only get mouse wheel events, and leave selection to the terminal always.

[1]: https://github.com/zulip/zulip-terminal

**Comment by trevarj** [comment]
Sadly, those are xterm and rxvt escape codes to turn on/off mouse capture. Nothing specific to which buttons.

xterm ones can be found here: https://www.xfree86.org/4.8.0/ctlseqs.html#Mouse%20Tracking

```
 CSI ? P m h      DEC Private Mode Set (DECSET)
 
                  P s = 1 0 0 0 → Send Mouse X & Y on button press and release. See the section Mouse Tracking.
                  P s = 1 0 0 1 → Use Hilite Mouse Tracking.
                  P s = 1 0 0 2 → Use Cell Motion Mouse Tracking.
```

**Comment by trevarj** [comment]
Thoughts on implementing highlighting and saving to the clipboard (cross-platform `clipboard` crate)?

**Comment by osa1** [comment]
I don't think this is worth adding more dependencies and code to maintain. We already have key bindings `shift-arrow` and page-up/page-down for scrolling, this is just for convenience. If there isn't an easy and low-maintenance way of implementing this then I think we can live with the existing key bindings.

**Comment by trevarj** [comment]
Understandable. 
The only thing I can think of is to have the first scroll on the mouse wheel toggle the mouse mode, and then when you don't scroll for a while it toggles it back off. Seems a little messy though.

**Comment by trevarj** [comment]
On my term `Alt+Shift` allows me to highlight then `Ctrl-c` to copy.

**Comment by osa1** [comment]
Yeah that works for me too, but not teaching every user how to select and copy is easier, and provides good UX. You do whatever you've been doing already and it works! Best UX.

**Pull request closed without merging**
