### PR TITLE
PKGBUILD: update name to tiny-git, sync other changes

### PR DESCRIPTION
**Pull request by ralphptorres**
Changes include:
- refactor and add functions
- disable link-time optimization (due to compilation issues in some machines)
- rename as tiny-git and update info

### CODE REVIEW

**Comment by osa1** [comment]
Does this file have to live in this repo? It's probably easier to update the AUR packages than this repo (I don't have as much time anymore), so I suggest we update the links (as in this PR) but remove the file. That way there will be just one copy of the PKGBUILD.

**Comment by ralphptorres** [comment]
I understand, would be fine with that.

**Comment by osa1** [comment]
Thanks. The README change in this PR are good, if you could revert the pkgbuild, or even better, delete it, we can merge this.

**Comment by ralphptorres** [comment]
Done

**Comment by ralphptorres** [comment]
Suggest updating commit message for merge. Thanks

**Comment by osa1** [comment]
Thanks!

**Pull request merged**
