### PR TITLE
Align nicks and messages

### PR DESCRIPTION
**Pull request by ii8**
Personally I prefer when nicks and wrapped messages are aligned, merge it if you agree I guess.
Otherwise it could also be made configurable quite easily.

Review carefully though, first time using rust so there are likely mistakes.

### CODE REVIEW

**Comment by Kabouik** [comment]
> merge it if you agree I guess

Just chiming in to say that I will use that if it is merged or made an option.

**Comment by trevarj** [comment]
We were having a discussion about this here: https://github.com/osa1/tiny/issues/169#issuecomment-614451588

**Comment by ii8** [comment]
Yes, I saw that discussion after having already made this PR(should have checked issues first :facepalm:)

I'm just going to leave this PR lying here until a decision is made.

**Comment by osa1** [comment]
Thanks for the PR. tiny's TUI is supposed to be compact and simple, but these kind of alternative layout requests came a few times in the past, and I don't want reject feature requests if they can be made optional without too much effort and in a way that doesn't make the default harder to maintain or test, or buggy, or slower.

So far I've seen these requested:

- Align after timestamps (this PR)
- Align after nicks (the issue linked above)

There are also other related requests like:

- Make it possible to configure timestamp formatting (#159)
- Make it possible to show timestamps always (I can't find the issue now, but I'm pretty sure this was requested in the past)

These are all related. For example, if we make timestamp formatting configurable we will have to remove `TS_WIDTH` in this PR (as the timestamp length won't be fixed anymore). So perhaps we should take the time to design and implement all these at once, as I'm pretty sure people will request these later again, and if we only do some of these we'll have to revert/update some of the changes in the previous PRs.

I'll try to see if there's an easy way to update the TUI to handle all these cases (align after timestamps, align after nicks, with configurable timestamp formatting), but if you've already looked at this ideas are always welcome.

**Comment by ii8** [comment]
For different length timestamps TS_WIDTH will just have to become a variable, no big upset. Showing timestamps always is just one more config option and if-branch.
This PR does align messages that wrap with the beginning of that message text. It does not align the ends of all nicks, but I'm not sure that's even desirable(Everything would move when somebody with a longer nick starts talking, long nicks would cause a lot of empty space etc.)

However if you want complete customizability, adding extra characters like vertical lines to separate timestamps and nicks, timestamps on the far right of the screen instead of the left etc. then things would probably have to be changed more radically.

**Comment by ii8** [comment]
Among those the only tricky one is aligning the end of nicks. It's not obvious how to deal with long nicks.

**Comment by Kabouik** [comment]
I realize with this discussion that the only thing I am missing currently is keeping nicknames left-aligned when no timestamp is shown. Apart from that, I like that timestamps are shown only when necessary, or that Tiny uses all space available and does not right-align nicknames, or wraps multi-line messages below the nickname of the poster (but it shouldn't wrap below the timestamps if nicks are left-aligned).

**Comment by meain** [comment]
I had tried doing this a while back. I used it for a while and switched back.

I don't think this should be the default though as the current config of tiny actually has a lot of usable space even on small screens.

About the max-length, I think there is limit of 9 chars for a nick. Not sure if all the implementations respect it though

**Comment by osa1** [comment]
This feature was implemented by @trevarj a while ago. Not officially announced in README and CHANGELOG yet (few bugs left to fix before that), but you can enable it in master branch by adding `layout: aligned` to your config. Closing.

**Pull request closed without merging**
