### PR TITLE
List cmd

### PR DESCRIPTION
**Pull request by flankstaek**
Added the /LIST command.

Let me know if you want any changes, first PR here, didn't see similar PR's or Contributing guidelines to follow so I just winged it.

### CODE REVIEW

**Comment by osa1** [comment]
Thanks for the patch.

I'm not sure if this is necessary as we kinda already have this feature: just send `LIST` in a server tab. Does this provide anything that sending `LIST` in a server tab does not?

**Comment by flankstaek** [comment]
Nope, just adds a slash command for it as I'm not sure it's entirely clear (without looking at source) that sending LIST to a server would work, but don't think this is necessary to merge if you don't want to.

**Comment by osa1** [comment]
> I'm not sure it's entirely clear (without looking at source) that sending LIST to a server would work

Right, we should mention README (maybe in "commands" section?) that sending a message in a server tab directly sends the message to the server, so it can be used to use parts of the IRC protocol that tiny doesn't support (like the `LIST` message). We could also give `LIST` as an example.

@flankstaek would you like to do that and update this PR? I think we don't need more code for this.

**Comment by flankstaek** [comment]
Reverted the code changes and added a section to the README.

**Comment by osa1** [comment]
Perfect, thanks @flankstaek !

**Pull request merged**
