### PR TITLE
Aur pkgbuild

### PR DESCRIPTION
**Pull request by wrycode**
@osa1 this is my first time using git. Hopefully I am doing this correctly.

I will to change the PKGBUILD's `# Maintainer: Nick Econopouly <wry@mm.st>` line to your contact information after making this pull request, just to see how Github handles the change.

### CODE REVIEW

**Comment by BrianOn99** [comment]
Just in case you will submit this aur, would `cargo +nightly build` be better?  Otherwise user's default toolchain might be changed.

**Comment by BrianOn99** [comment]
I can verify that this PKGBUILD works, but on Arch we needs `pkg-config` installed first.  It is missing in `makedepends`.

**Comment by wrycode** [comment]
@BrianOn99 thank you, I will update the cargo command and remove the rustup commands.

> I can verify that this PKGBUILD works, but on Arch we needs pkg-config installed first. It is missing in makedepends

`pkg-config` is a member of the `base-devel` group, and therefore should not be included according to the Arch Wiki's
[PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends) page.

**Comment by BrianOn99** [comment]
Nice catch.

**Comment by osa1** [comment]
Thanks!

Just a comment, I think maintainer should point at you or @BrianOn99 because I have no idea how to maintain this, I don't even use Arch Linux :) Could you update that?

If none of you want to maintain this then it's fine, just let me know.

**Comment by BrianOn99** [comment]
@wrycode Feel free to become the maintainer!

**Comment by wrycode** [comment]
I'm happy to maintain it.

**Comment by osa1** [comment]
Thanks!

**Pull request merged**
