### PR TITLE
Statusline implementation

### PR DESCRIPTION
**Pull request by meain**
I needed the `statusline` piece from #109 . But I was having a lot of trouble merging the current master to that branch. So I rewrote it on top of the current master.

### CODE REVIEW

**Comment by meain** [comment]
Hey @osa1 , anything else I could do to get this merged?

**Comment by meain** [comment]
I see that you have an `async_refactor` branch which you are working on. I guess I could resubmit it once you are done with that.

**Comment by osa1** [comment]
@meain Sorry for the delay, and thanks! I'll port this over to the new branch (which should be a matter of copy-pasta as the TUI code is not changed)

**Comment by osa1** [comment]
Merged to `async_refactor` as 8fe5ae4.

**Pull request merged**
